version: '3.5'

services:
  #URL https://localhost:9443
  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - 9443:9443
    volumes:
        - data:/data
        - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  localstack:
    container_name: localstack_main
    image: localstack/localstack:2.0.0
    ports:
      - 4566:4566
    environment:
      - SERVICES=sns,sqs
    volumes:
      - "./localstack.sh:/docker-entrypoint-initaws.d/make-services.sh"
    networks:
      - local

volumes:
  data:
networks:
  local:
    driver: bridge
